# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42b7e00101f52a88f4bbc74f28d31eea0bdf35622fa474bbbf90c46e50da2cffea243d67b77a0ab71b1c1bef429589ceedcd5d080e45462c4cd231360cc3787f

test:
  secret_key_base: 531a2d120a60247f8dfeb9595b955a712efc20f8c76ef25de9fff62effb7af20c6357414dfab022642497ba68940a26b46e19d97a58f07b9a236df9c2fa1b7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
